import { itemBook } from '../utils/types'

const initBooks: itemBook[] = [
  {
    id: 1,
    name: 'Refactoring',
    author: 'Martin Fowler',
    topic: 'Programming',
    tag: 'refactoring',
  },
  {
    id: 2,
    name: 'Design Data-Intensive Applications',
    author: 'Martin Kleppman',
    topic: 'Database',
    tag: 'design data-intensive applications',
  },
  {
    id: 3,
    name: 'The Phoenix Project',
    author: 'Gene Kim',
    topic: 'Devops',
    tag: 'the phoenix project',
  },
  {
    id: 4,
    name: 'JavaScript : The Good Parts',
    author: 'Douglas Crockford',
    topic: 'Frontend',
    tag: 'javascript : the good parts',
  },
  {
    id: 5,
    name: 'Node.js Design Patterns',
    author: 'Mario Casciaro',
    topic: 'Backend',
    tag: 'nodejs design patterns',
  },
  {
    id: 6,
    name: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    topic: 'Programming',
    tag: 'clean code: a handbook of agile software craftsmanship',
  },
  {
    id: 7,
    name: 'Database Systems: The Complete Book',
    author: 'Hector Garcia-Molina',
    topic: 'Database',
    tag: 'database system',
  },
  {
    id: 8,
    name: 'Continuous Delivery: Reliable Software Releases through Build, Test, and Deployment Automation',
    author: 'Jez Humble and David Farley',
    topic: 'Devops',
    tag: 'continuous delivery: reliable software releases through build, test, and deployment automation',
  },
  {
    id: 9,
    name: 'Eloquent JavaScript',
    author: 'Marijn Haverbeke',
    topic: 'Frontend',
    tag: 'eloquent javascript',
  },
  {
    id: 10,
    name: 'Python Crash Course',
    author: 'Eric Matthes',
    topic: 'Programming',
    tag: 'python crash course',
  },
  {
    id: 11,
    name: 'Introduction to the Theory of Computation',
    author: 'Michael Sipser',
    topic: 'Programming',
    tag: 'introduction to the theory of computation',
  },
  {
    id: 12,
    name: 'MongoDB: The Definitive Guide',
    author: 'Kristina Chodorow',
    topic: 'Database',
    tag: 'mongodb: the definitive guide',
  },
  {
    id: 13,
    name: 'Kubernetes Up and Running',
    author: 'Kelsey Hightower',
    topic: 'Devops',
    tag: 'kubernetes up and running',
  },
  {
    id: 14,
    name: 'React Up and Running',
    author: 'Stoyan Stefanov',
    topic: 'Frontend',
    tag: 'react up and running',
  },
  {
    id: 15,
    name: 'Node.js in Action',
    author: 'Mike Cantelon',
    topic: 'Backend',
    tag: 'node.js in action',
  },
  {
    id: 16,
    name: 'Agile Estimating and Planning',
    author: 'Mike Cohn',
    topic: 'Devops',
    tag: 'agile estimating and planning',
  },
  {
    id: 17,
    name: 'Head First Java',
    author: 'Kathy Sierra and Bert Bates',
    topic: 'Programming',
    tag: 'head first java',
  },
  {
    id: 18,
    name: 'Learning SQL',
    author: 'Alan Beaulieu',
    topic: 'Database',
    tag: 'learning sql',
  },
  {
    id: 19,
    name: 'The Pragmatic Programmer',
    author: 'Andrew Hunt and David Thomas',
    topic: 'Programming',
    tag: 'the pragmatic programmer',
  },
  {
    id: 20,
    name: 'Docker Deep Dive',
    author: 'Nigel Poulton',
    topic: 'Devops',
    tag: 'docker deep dive',
  },
  {
    id: 21,
    name: "Clean Architecture: A Craftsman's Guide to Software Structure and Design",
    author: 'Robert C. Martin',
    topic: 'Programming',
    tag: "clean architecture: a craftsman's guide to software structure and design",
  },
  {
    id: 22,
    name: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen',
    topic: 'Programming',
    tag: 'introduction to algorithms',
  },
  {
    id: 23,
    name: 'SQL Performance Explained',
    author: 'Markus Winand',
    topic: 'Database',
    tag: 'sql performance explained',
  },
  {
    id: 24,
    name: 'Continuous Integration: Improving Software Quality and Reducing Risk',
    author: 'Paul M. Duvall',
    topic: 'Devops',
    tag: 'continuous integration: improving software quality and reducing risk',
  },
  {
    id: 25,
    name: 'React.js Essentials',
    author: 'Artemij Fedosejev',
    topic: 'Frontend',
    tag: 'react.js essentials',
  },
  {
    id: 26,
    name: 'Node.js Web Development',
    author: 'David Herron',
    topic: 'Backend',
    tag: 'node.js web development',
  },
  {
    id: 27,
    name: 'Git Pro',
    author: 'Scott Chacon and Ben Straub',
    topic: 'Devops',
    tag: 'git pro',
  },
  {
    id: 28,
    name: 'Python Programming for the Absolute Beginner',
    author: 'Michael Dawson',
    topic: 'Programming',
    tag: 'python programming for the absolute beginner',
  },
  {
    id: 29,
    name: 'MySQL High Availability: Tools for Building Robust Data Centers',
    author: 'Charles Bell',
    topic: 'Database',
    tag: 'mysql high availability: tools for building robust data centers',
  },
  {
    id: 30,
    name: 'Infrastructure as Code: Managing Servers in the Cloud',
    author: 'Kief Morris',
    topic: 'Devops',
    tag: 'infrastructure as code: managing servers in the cloud',
  },
  {
    id: 31,
    name: 'Learning React: Functional Web Development with React and Redux',
    author: 'Alex Banks and Eve Porcello',
    topic: 'Frontend',
    tag: 'learning react: functional web development with react and redux',
  },
  {
    id: 32,
    name: 'Express.js in Action',
    author: 'Evan Hahn',
    topic: 'Backend',
    tag: 'express.js in action',
  },
  {
    id: 33,
    name: 'Continuous Delivery and DevOps: A Quickstart Guide',
    author: 'Paul Swartout',
    topic: 'Devops',
    tag: 'continuous delivery and devops: a quickstart guide',
  },
  {
    id: 34,
    name: 'C# in Depth',
    author: 'Jon Skeet',
    topic: 'Programming',
    tag: 'c# in depth',
  },
  {
    id: 35,
    name: 'NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence',
    author: 'Pramod J. Sadalage and Martin Fowler',
    topic: 'Database',
    tag: 'nosql distilled: a brief guide to the emerging world of polyglot persistence',
  },
  {
    id: 36,
    name: 'Docker for Developers',
    author: 'Chris Tankersley',
    topic: 'Devops',
    tag: 'docker for developers',
  },
  {
    id: 37,
    name: 'React Design Patterns and Best Practices',
    author: 'Carlos Santana Roldán',
    topic: 'Frontend',
    tag: 'react design patterns and best practices',
  },
  {
    id: 38,
    name: 'Building RESTful Web Services with Go: Learn how to build powerful RESTful APIs with Golang that scale gracefully',
    author: 'Naveen Kumar',
    topic: 'Backend',
    tag: 'building restful web services with go: learn how to build powerful restful apis with golang that scale gracefully',
  },
  {
    id: 39,
    name: 'The DevOps Handbook: How to Create World-Class Agility, Reliability, & Security in Technology Organizations',
    author: 'Gene Kim, Patrick Debois, John Willis, and Jez Humble',
    topic: 'Devops',
    tag: 'the devops handbook: how to create world-class agility, reliability, & security in technology organizations',
  },
  {
    id: 40,
    name: 'Python Crash Course: A Hands-On, Project-Based Introduction to Programming',
    author: 'Eric Matthes',
    topic: 'Programming',
    tag: 'python crash course: a hands-on, project-based introduction to programming',
  },
]

export default initBooks
