const allBooks = [
  {
    id: 1,
    name: 'Refactoring',
    author: 'Martin Fowler',
    topic: 'Programming',
  },
  {
    id: 2,
    name: 'Design Data-Intensive Applications',
    author: 'Martin Kleppman',
    topic: 'Database',
  },
  {
    id: 3,
    name: 'The Phoenix Project',
    author: 'Gene Kim',
    topic: 'Devops',
  },
  {
    id: 4,
    name: 'JavaScript: The Good Parts',
    author: 'Douglas Crockford',
    topic: 'Frontend',
  },
  {
    id: 5,
    name: 'Node.js Design Patterns',
    author: 'Mario Casciaro',
    topic: 'Backend',
  },
  {
    id: 6,
    name: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    topic: 'Programming',
  },
  {
    id: 7,
    name: 'Database Systems: The Complete Book',
    author: 'Hector Garcia-Molina',
    topic: 'Database',
  },
  {
    id: 8,
    name: 'Continuous Delivery: Reliable Software Releases through Build, Test, and Deployment Automation',
    author: 'Jez Humble and David Farley',
    topic: 'Devops',
  },
  {
    id: 9,
    name: 'Eloquent JavaScript',
    author: 'Marijn Haverbeke',
    topic: 'Frontend',
  },
  {
    id: 10,
    name: 'Python Crash Course',
    author: 'Eric Matthes',
    topic: 'Programming',
  },
  {
    id: 11,
    name: 'Introduction to the Theory of Computation',
    author: 'Michael Sipser',
    topic: 'Programming',
  },
  {
    id: 12,
    name: 'MongoDB: The Definitive Guide',
    author: 'Kristina Chodorow',
    topic: 'Database',
  },
  {
    id: 13,
    name: 'Kubernetes Up and Running',
    author: 'Kelsey Hightower',
    topic: 'Devops',
  },
  {
    id: 14,
    name: 'React Up and Running',
    author: 'Stoyan Stefanov',
    topic: 'Frontend',
  },
  {
    id: 15,
    name: 'Node.js in Action',
    author: 'Mike Cantelon',
    topic: 'Backend',
  },
  {
    id: 16,
    name: 'Agile Estimating and Planning',
    author: 'Mike Cohn',
    topic: 'Devops',
  },
  {
    id: 17,
    name: 'Head First Java',
    author: 'Kathy Sierra and Bert Bates',
    topic: 'Programming',
  },
  {
    id: 18,
    name: 'Learning SQL',
    author: 'Alan Beaulieu',
    topic: 'Database',
  },
  {
    id: 19,
    name: 'The Pragmatic Programmer',
    author: 'Andrew Hunt and David Thomas',
    topic: 'Programming',
  },
  {
    id: 20,
    name: 'Docker Deep Dive',
    author: 'Nigel Poulton',
    topic: 'Devops',
  },
  {
    id: 21,
    name: 'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design',
    author: 'Robert C. Martin',
    topic: 'Programming',
  },
  {
    id: 22,
    name: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen',
    topic: 'Programming',
  },
  {
    id: 23,
    name: 'SQL Performance Explained',
    author: 'Markus Winand',
    topic: 'Database',
  },
  {
    id: 24,
    name: 'Continuous Integration: Improving Software Quality and Reducing Risk',
    author: 'Paul M. Duvall',
    topic: 'Devops',
  },
  {
    id: 25,
    name: 'React.js Essentials',
    author: 'Artemij Fedosejev',
    topic: 'Frontend',
  },
  {
    id: 26,
    name: 'Node.js Web Development',
    author: 'David Herron',
    topic: 'Backend',
  },
  {
    id: 27,
    name: 'Git Pro',
    author: 'Scott Chacon and Ben Straub',
    topic: 'Devops',
  },
  {
    id: 28,
    name: 'Python Programming for the Absolute Beginner',
    author: 'Michael Dawson',
    topic: 'Programming',
  },
  {
    id: 29,
    name: 'MySQL High Availability: Tools for Building Robust Data Centers',
    author: 'Charles Bell',
    topic: 'Database',
  },
  {
    id: 30,
    name: 'Infrastructure as Code: Managing Servers in the Cloud',
    author: 'Kief Morris',
    topic: 'Devops',
  },
  {
    id: 31,
    name: 'Learning React: Functional Web Development with React and Redux',
    author: 'Alex Banks and Eve Porcello',
    topic: 'Frontend',
  },
  {
    id: 32,
    name: 'Express.js in Action',
    author: 'Evan Hahn',
    topic: 'Backend',
  },
  {
    id: 33,
    name: 'Continuous Delivery and DevOps: A Quickstart Guide',
    author: 'Paul Swartout',
    topic: 'Devops',
  },
  {
    id: 34,
    name: 'C# in Depth',
    author: 'Jon Skeet',
    topic: 'Programming',
  },
  {
    id: 35,
    name: 'NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence',
    author: 'Pramod J. Sadalage and Martin Fowler',
    topic: 'Database',
  },
  {
    id: 36,
    name: 'Docker for Developers',
    author: 'Chris Tankersley',
    topic: 'Devops',
  },
  {
    id: 37,
    name: 'React Design Patterns and Best Practices',
    author: 'Carlos Santana Roldán',
    topic: 'Frontend',
  },
  {
    id: 38,
    name: 'Building RESTful Web Services with Go: Learn how to build powerful RESTful APIs with Golang that scale gracefully',
    author: 'Naveen Kumar',
    topic: 'Backend',
  },
  {
    id: 39,
    name: 'The DevOps Handbook: How to Create World-Class Agility, Reliability, & Security in Technology Organizations',
    author: 'Gene Kim, Patrick Debois, John Willis, and Jez Humble',
    topic: 'Devops',
  },
  {
    id: 40,
    name: 'Python Crash Course: A Hands-On, Project-Based Introduction to Programming',
    author: 'Eric Matthes',
    topic: 'Programming',
  }
];

export default allBooks;
